### ISSUE TITLE
Multilayer - Assign Colors

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/GHAP#136] opened 2022-11-05 21:40 UTC
I hope you’re well – really looking forward to the workshop in a couple of weeks (and I ran into Matthew Martin this afternoon who is also humming along with his talk). I’ve had a crack at putting up my work on morocco leather as a multilayer, so that I can show different colours of morocco leather bookbindings geocoded by the people who owned them – you can see the first results here: https://www.tlcmap.org/view/collection-timeline.html?load=https://www.tlcmap.org/ghap/publiccollections/12/json – but I would really like to be able to choose what colours the different layers appear in, so that they correspond with the binding colours (yellow, red, black, brown, green, blue and perhaps grey for unlisted) – is this possible? No rush to answer this – or at all if you’re too busy!

**Comment by BillPascoe** [comment] 2023-07-07 06:17
Duplicate of anothe issue and woudl have been sorted with customisation enhancements.

**Closed by BillPascoe** 2023-07-07 06:17 UTC
Labels: enhancement, priority 2, Scope 2, Allocate Budget
